#!/bin/bash

mode=''
running='true'

echo ""
echo -e "\x1B[1mHello ${USER}!"
echo -e '\x1B[0mhere are the possible commands:'
echo -e ""
echo -e '\x1B[1mcreate \x1B[92m(Create something that doesnt exist yet)\x1B[0m'
echo -e '\x1B[1mdevelop \x1B[92m(Develop or modify files with existing templates/code)\x1B[0m'
echo -e '\x1B[1mdeploy \x1B[92m(Deploy Project or login to a server or deploy with docker)\x1B[0m'
echo ""

read -p 'enter mode: ' mode

if [[ $mode == 'create' ]]
then 
    echo ""
    echo $mode mode initialized
    echo ""
elif [[ $mode == 'develop' ]]
then 
    echo ""    
    echo develop mode engaged
    echo ""
elif [[ $mode == 'deploy' ]]
then
    echo ""
    echo $mode mode started
    echo ""
else
    echo ""
    echo 'Input was not valid, please check your input spelling'
    echo ""
fi
