#!/bin/bash

#add show env function below here
#print the env before running loop

echo 'type qq to quit'
vvs() {
  d=$(pwd)
  ~/scripts/wtcli/fbin/vvs/envset Dir $d

  read -p "--> " ff
  if [[ $ff == 'qq' ]]
  then 
    clear
    ~/scripts/wtcli/wtcli
    ~/scripts/wtcli/fbin/vvs/envset isRunning -1

  elif [[ $ff == 'env' ]]
  then 
    echo ""
    ~/scripts/wtcli/fbin/vvs/envget
    vvs
  elif [[ -e /usr/bin/$ff ]]
  then 
    read -p "Underlying Command Found Enter full command: " cc
    eval $cc
    vvs
  elif [[ -e /bin/$ff ]]
  then 
    read -p "Underlying Command Found Enter full command: " cc
    eval $cc
    vvs
  else
    ~/scripts/wtcli/fbin/vvs/$ff
    vvs
  fi
}
vvs

