#!/bin/bash

develop() {
    
    echo "development mode started"
    pwd
    read input
    if [[ $input == 'q' ]]
    then
        echo "exiting back"
        ~/scripts/wtcli/wtcli
    else
        ~/scripts/wtcli/fbin/fdev/$input
        ~/scripts/wtcli/fbin/develop
    fi
}
develop
