#!/bin/bash
echo ""
echo this is create new html file with css and js
read -p "Enter a name for folder: " fName
read -p "Enter a name for files (optional): " fileName
cd $(pwd)

if [[ -z $fName ]]
then
    echo 'name is empty, you must enter a folder name'
    ~/scripts/wtcli/fbin/html
elif [[ $fName = 'q' ]]
then
    echo 'exiting'
elif [[ -n $fileName ]]
then 
    mkdir $fName
    touch ./$fName/$fileName.html
    touch ./$fName/$fileName.css
    touch ./$fName/$fileName.js
    ls
    ~/scripts/wtcli/fbin/create
else
    mkdir $fName
    touch ./$fName/index.html
    touch ./$fName/index.css
    touch ./$fName/index.js
    ls
    ~/scripts/wtcli/fbin/create
fi