#!/bin/bash

appendfromto() {
    fromfilePath=$1
    tofilePath=$2
    workingdir=$(pwd)
    echo $workingdir"/"$tofilePath
    echo $tofilePath
    echo $fromfilePath
    sed "/<body>/r $fromfilePath" $workingdir"/"$tofilePath
}
appendfromto $1 $2