#!/bin/bash

# get the env variables and echo them

envget() {
    if [[ $1 ]]
    then
      ggrep -oP "(?<=$1:).*" ~/scripts/wtcli/env/env
    else 
      cat ~/scripts/wtcli/env/env
    fi
}

envget $1