#!/bin/bash


getclosingtag() {


PATTERN=$(~/scripts/wtcli/fbin/vvs/envget match)
RMTAGS="< >"
NAME=$(tr -d "$RMTAGS" <<< $PATTERN);
echo closing tags are: $NAME;
CLOSINGTAGS=$(echo "</$NAME>")
echo $CLOSINGTAGS

}
getclosingtag
