#!/bin/bash


rmm() {

FILE=$(~/scripts/wtcli/fbin/vvs/envget workingfile)
echo $FILE
PATTERN=$(~/scripts/wtcli/fbin/vvs/envget match)
LINESTART=$(~/scripts/wtcli/fbin/vvs/getlinenum $PATTERN)

CLOSINGTAGS=$(~/scripts/wtcli/fbin/vvs/getclosingtag)
LINEEND=$(~/scripts/wtcli/fbin/vvs/getlinenumend $PATTERN)

# echo "THE CLOSING TAGS ARE: $CLOSINGTAGS"
echo line start $LINESTART
echo line end $LINEEND
# FULLMATCH=$(echo "$PATTERN.*$CLOSINGTAGS")

sed -i -e "$LINESTART,${LINEEND} d" $FILE
# sed "15,97d" $FILE

}
rmm $1

# $1 is not necessary at the moment. The Pattern that is matched is in ENV
